version: "3.8"

services:
  nic-backend:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=nic
      - POSTGRESQL_PASSWORD=123
      - POSTGRESQL_DATABASE=dev