name: Testes

on: [push, pull_request]

jobs:
  setup:
    name: Execução dos Testes Unitários & E2E
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_versions: ['16', '18', '>=18']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_versions }}
          cache: 'npm'

      - name: Instalando as dependências
        run: npm ci
    
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Fazendo migrações do banco de dados
      run: npx prisma migrate dev --name tests      

    - name: Subindo o container do PostgreSQL
      run: docker-compose up -d
  
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        DATABASE_URL: ${{ secrets.DB_URL }}
  
  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Executando testes
      run: npm run test:ci