name: (BACKEND) Testes Unitários & E2E

on: [push, pull_request]

env:
  BACKEND_DIR: backend
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  DATABASE_URL: ${{ secrets.DB_URL }}

jobs:
  setup:
    name: Configuração inicial
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_versions: ['16', '18', '>=18']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_versions }}
          cache: 'npm'
          cache-dependency-path: ${{ env.BACKEND_DIR }}/package-lock.json

      - name: Instalando as dependências
        run: npm ci
        working-directory: ${{ env.BACKEND_DIR }}
    
  build:
    needs: setup
    runs-on: ubuntu-latest

    services:
      PostgreSQL:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: ${{ secrets.DB_USER }}
          POSTGRESQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRESQL_DATABASE: ${{ secrets.DB_NAME }}

    steps:
      - uses: actions/checkout@v3

      - name: Fazendo migrações do banco de dados
        run: npx prisma migrate dev --name tests
        working-directory: ${{ env.BACKEND_DIR }}

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Executando testes
        run: npm ci && npm run test:ci
        working-directory: ${{ env.BACKEND_DIR }}